export const stores = {
    "AR": {"name": "Argentina", "alpha3": "ARG", "defaultCurrency": "ARS"},
    "AU": {"name": "Australia", "alpha3": "AUS", "defaultCurrency": "AUD"},
    "AT": {"name": "Austria", "alpha3": "AUT", "defaultCurrency": "EUR"},
    "BE": {"name": "Belgium", "alpha3": "BEL", "defaultCurrency": "EUR"},
    "BR": {"name": "Brazil", "alpha3": "BRA", "defaultCurrency": "BRL"},
    "BG": {"name": "Bulgaria", "alpha3": "BGR", "defaultCurrency": "EUR"},
    "CA": {"name": "Canada", "alpha3": "CAN", "defaultCurrency": "CAD"},
    "CL": {"name": "Chile", "alpha3": "CHL", "defaultCurrency": "CLP"},
    "CO": {"name": "Colombia", "alpha3": "COL", "defaultCurrency": "COP"},
    "HR": {"name": "Croatia", "alpha3": "HRV", "defaultCurrency": "EUR"},
    "CY": {"name": "Cyprus", "alpha3": "CYP", "defaultCurrency": "EUR"},
    "CZ": {"name": "Czech Republic", "alpha3": "CZE", "defaultCurrency": "CZK"},
    "DK": {"name": "Denmark", "alpha3": "DNK", "defaultCurrency": "DKK"},
    "EE": {"name": "Estonia", "alpha3": "EST", "defaultCurrency": "EUR"},
    "FI": {"name": "Finland", "alpha3": "FIN", "defaultCurrency": "EUR"},
    "FR": {"name": "France", "alpha3": "FRA", "defaultCurrency": "EUR"},
    "DE": {"name": "Germany", "alpha3": "DEU", "defaultCurrency": "EUR"},
    "GR": {"name": "Greece", "alpha3": "GRC", "defaultCurrency": "EUR"},
    "HK": {"name": "Hong Kong", "alpha3": "HKG", "defaultCurrency": "HKD"},
    "HU": {"name": "Hungary", "alpha3": "HUN", "defaultCurrency": "EUR"},
    "IE": {"name": "Ireland", "alpha3": "IRL", "defaultCurrency": "EUR"},
    "IL": {"name": "Israel", "alpha3": "ISR", "defaultCurrency": "EUR"},
    "IT": {"name": "Italy", "alpha3": "ITA", "defaultCurrency": "EUR"},
    "JP": {"name": "Japan", "alpha3": "JPN", "defaultCurrency": "JPY"},
    "LV": {"name": "Latvia", "alpha3": "LVA", "defaultCurrency": "EUR"},
    "LT": {"name": "Lithuania", "alpha3": "LTU", "defaultCurrency": "EUR"},
    "LU": {"name": "Luxembourg", "alpha3": "LUX", "defaultCurrency": "EUR"},
    "MT": {"name": "Malta", "alpha3": "MLT", "defaultCurrency": "EUR"},
    "MX": {"name": "Mexico", "alpha3": "MEX", "defaultCurrency": "MXN"},
    "NL": {"name": "Netherlands", "alpha3": "NLD", "defaultCurrency": "EUR"},
    "NZ": {"name": "New Zealand", "alpha3": "NZL", "defaultCurrency": "NZD"},
    "NO": {"name": "Norway", "alpha3": "NOR", "defaultCurrency": "NOK"},
    "PE": {"name": "Peru", "alpha3": "PER", "defaultCurrency": "PEN"},
    "PL": {"name": "Poland", "alpha3": "POL", "defaultCurrency": "PLN"},
    "PT": {"name": "Portugal", "alpha3": "PRT", "defaultCurrency": "EUR"},
    "RO": {"name": "Romania", "alpha3": "ROU", "defaultCurrency": "EUR"},
    "RU": {"name": "Russia", "alpha3": "RUS", "defaultCurrency": "RUB"},
    "SK": {"name": "Slovakia", "alpha3": "SVK", "defaultCurrency": "EUR"},
    "SI": {"name": "Slovenia", "alpha3": "SVN", "defaultCurrency": "EUR"},
    "ZA": {"name": "South Africa", "alpha3": "ZAF", "defaultCurrency": "ZAR"},
    "KR": {"name": "South Korea", "alpha3": "KOR", "defaultCurrency": "KRW"},
    "ES": {"name": "Spain", "alpha3": "ESP", "defaultCurrency": "EUR"},
    "SE": {"name": "Sweden", "alpha3": "SWE", "defaultCurrency": "SEK"},
    "CH": {"name": "Switzerland", "alpha3": "CHE", "defaultCurrency": "CHF"},
    "GB": {"name": "United Kingdom", "alpha3": "GBR", "defaultCurrency": "GBP"},
    "US": {"name": "United States", "alpha3": "USA", "defaultCurrency": "USD"}
}
